services:
  postgres:
    image: postgres:15
    container_name: siac-postgres
    environment:
      - POSTGRES_DB=siac_db
      - POSTGRES_USER=siac
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infra/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "25432:5432"
    networks:
      - siac-network
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: siac-backend
    ports:
      - "18000:8000"
    environment:
      - MQTT_HOST=mosquitto_secure
      - MQTT_PORT=1883
      - MQTT_USERNAME=nodered
      - MQTT_PASSWORD=nodered
      - MQTT_TLS_ENABLED=false
      - MQTT_CA_CERT=/app/certs/ca.crt
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=siac-token
      - INFLUXDB_ORG=siac
      - INFLUXDB_BUCKET=bucket_iot
      - DATABASE_URL=postgresql://siac:password@postgres:5432/siac_db
      - PYTHONUNBUFFERED=1
      - CORS_ORIGINS=http://localhost:5173,http://127.0.0.1:5173,http://172.21.0.8:3000/
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - ../iot-security/mosquitto/certs:/app/certs:ro
    networks:
      - siac-network
    restart: unless-stopped

  frontend:
    image: node:20-alpine
    container_name: siac-frontend
    working_dir: /app
    command: ["sh", "-c", "npm install && npm run dev -- --host 0.0.0.0"]
    ports:
      - "5173:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:18000
    depends_on:
      - backend
    networks:
      - siac-network

networks:
  siac-network:
    external: true

volumes:
  postgres_data:
